/** The knob glossary's module-specific half (paramInfo.ts has the common
 *  words): a module's own meaning for a word (MODULE_TERMS, matched like the
 *  common ones), and single controls (OVERRIDES, by `type:param`; the synth
 *  voices' are in paramGlossary2.ts). */
import { MORE_OVERRIDES } from './paramGlossary2'

export interface ParamTerm {
  /** Matched against the label in upper case, whole, then without its leading words. */
  match: RegExp
  what: string
}

const ADSR_DECAY: ParamTerm = { match: /^DECAY$/, what: 'After the attack, how long the note takes to fall to the SUSTAIN level.' }
const FM_KNOBS: ParamTerm[] = [
  { match: /^RATIO$/, what: 'The modulator’s pitch against the note: whole numbers sound musical, odd ones clangy and bell-like.' },
  { match: /^(DEPTH|INDEX)$/, what: 'How hard the modulator bends the note: from a plain tone to bright, brassy, then metallic.' },
  { match: /^MOD DEC$/, what: 'How fast the brightness dies away after each hit: short for plucks and drums, long for pads.' },
  { match: /^SWEEP$/, what: 'A quick pitch drop at the start of each hit: the thud of a kick, the zap of a tom.' },
]

export const MODULE_TERMS: Record<string, ParamTerm[]> = {
  mono: [ADSR_DECAY],
  studio: [ADSR_DECAY],
  adsr: [ADSR_DECAY],
  padsr: [ADSR_DECAY],
  lockstep: [
    ...FM_KNOBS,
    { match: /^DELAY$/, what: 'How much of this track goes to the shared delay.' },
    { match: /^DLY TIME$/, what: 'The shared delay’s time: how far apart the echoes are.' },
    { match: /^DLY FDBK$/, what: 'How many times the shared delay repeats.' },
    { match: /^NOTE$/, what: 'The selected step’s note, in semitones from the track’s root.' },
    { match: /^COND$/, what: 'When the step plays: always, on a chance, or only on some passes round the loop (1:2 = every other time).' },
    { match: /^ALGO$/, what: 'The FM algorithm: how the operators are wired (who modulates whom). Each one gives a family of sounds.' },
    { match: /^ROOT$/, what: 'The track’s base note: every step’s NOTE counts from here.' },
    { match: /^SPEED$/, what: 'How fast this track steps compared with the others (half, double…): for polyrhythms.' },
    { match: /^RETRIG$/, what: 'A ratchet: the selected step fires 2, 3 or 4 quick hits instead of one (rolls, stutters).' },
    { match: /^MICRO$/, what: 'Nudges the selected step early or late, in 24ths of a step: lazy bass, pushed hats, human feel.' },
    { match: /^LFO SPD$/, what: 'How fast the track’s LFO sweeps, in time with the tempo: once every 4 bars up to every 16th.' },
    { match: /^LFO AMT$/, what: 'How far the LFO moves its destination, either way from the middle (none at 0).' },
    { match: /^LFO DEST$/, what: 'What the LFO moves: the pitch (vibrato, sirens), FM depth, cutoff (wobble), level (tremolo), pan (auto-pan) or the delay send.' },
    { match: /^REVERB$/, what: 'How much of this track goes to the shared plate reverb.' },
  ],
  sketchbook: [
    ...FM_KNOBS,
    { match: /^SHAPE$/, what: 'The waveform: smooth and round to bright and buzzy.' },
    { match: /^PLUCK$/, what: 'How hard the string is plucked: soft thumb to sharp pick.' },
    { match: /^SUB$/, what: 'A sub-oscillator an octave down: weight under the sound.' },
    { match: /^SPREAD$/, what: 'How wide the swarm of voices is spread across the stereo field.' },
    { match: /^WAVE$/, what: 'The phase-distortion wave: saw, square, pulse, resonant shapes.' },
    { match: /^DCW$/, what: 'Phase distortion amount (Casio’s “DCW”): like a filter cutoff, from a pure sine to the full bright wave.' },
    { match: /^COLOR$/, what: 'The colour of the noise grains: dark rumble to bright hiss.' },
    { match: /^POSITION$/, what: 'Where in the wavetable it plays: each position is a different wave.' },
    { match: /^WARP$/, what: 'Bends the wave out of shape: more and more harmonics.' },
    { match: /^TWIN$/, what: 'A second, detuned copy of the voice: wider and thicker.' },
    { match: /^MIX$/, what: 'How much of the effect you hear.' },
    { match: /^BITS$/, what: 'Bit depth: fewer bits, crunchier and noisier.' },
    { match: /^LFO TO$/, what: 'What the LFO moves.' },
  ],
  lattice: [
    { match: /^LOOP$/, what: 'How many columns this layer loops over before going round again.' },
    { match: /^RATE$/, what: 'How fast this layer steps (or its balls fall), against the tempo.' },
    { match: /^SWING$/, what: 'Swings this layer: every other step comes late, for a shuffle (the other layers keep straight).' },
  ],
  pocket: [{ match: /^A PITCH$/, what: 'The selected sound’s pitch (hold a step to lock it there only).' }],
  pocketbass: [{ match: /^A TONE$/, what: 'Brightness: opens the filter (hold a step to lock it there only).' }],
  pocketmelody: [{ match: /^A TONE$/, what: 'Brightness: opens the filter (hold a step to lock it there only).' }],
  pocketoffice: [
    { match: /^A TONE$/, what: 'The selected sound’s pitch or brightness (hold a step to lock it there only).' },
    { match: /^B LENGTH$/, what: 'How long the selected sound lasts: a key’s ring, the carriage’s run, the phone’s trill.' },
  ],
  pocketrobot: [
    { match: /^A TONE$/, what: 'Brightness: how far the filter opens (each note also sweeps it a little).' },
    { match: /^B DECAY$/, what: 'How much effect: the echo’s level and repeats, or how hard the crush.' },
  ],
  pocketarcade: [
    { match: /^A TONE$/, what: 'Vibrato: how far held notes wobble once they’ve sounded a moment (the classic delayed game vibrato).' },
    { match: /^B DECAY$/, what: 'How long each lead note takes to fade, in the old chips’ 16 steps of volume.' },
  ],
  spring: [{ match: /^DECAY$/, what: 'How long the spring keeps ringing after the sound stops.' }],
  plate: [{ match: /^DECAY$/, what: 'How long the reverb tail lasts: a short room to a huge hall.' }],
  vocoder: [
    { match: /^ATTACK$/, what: 'How fast each band opens when the voice gets louder: fast for crisp words.' },
    { match: /^RELEASE$/, what: 'How long each band hangs on after the voice stops: longer is smoother and blurrier.' },
    { match: /^TUNE$/, what: 'The built-in carrier’s pitch (used when nothing is patched to CARRIER).' },
  ],
  master: [{ match: /^RELEASE$/, what: 'How fast the limiter lets go after a peak: fast is loud and pumpy, slow is smooth.' }],
  djmix: [
    { match: /^FILTER$/, what: 'One-knob filter: left of centre cuts the highs, right cuts the lows; middle is off.' },
    { match: /^(LOW|MID|HI)$/, what: 'Kill EQ: all the way down removes that band entirely (drop the bass, bring it back on the one).' },
  ],
  console: [{ match: /^TONE$/, what: 'Tilt EQ: left is darker and warmer, right is brighter and thinner.' }],
  vision: [{ match: /^RATE$/, what: 'How fast the scene lives.' }],
  visioncore: [{ match: /^RATE$/, what: 'How fast the scene lives.' }],
}

const o: Record<string, string> = {
  // the systems
  'mono:wave': 'Blends from saw (bright, buzzy) to pulse (hollow, reedy).',
  'mono:mode': 'ENV: notes start and stop with the envelope. DRONE: the sound never stops (tweak away).',
  'studio:fm1': 'How much oscillator 2 bends oscillator 1’s pitch: a growl, then clangy bells.',
  'studio:lf3': 'AUDIO: oscillator 3 is a third voice. LOW: it slows into an LFO for vibrato and sweeps.',
  'studio:m1': 'How loud oscillator 1 is in the mixer.',
  'studio:m2': 'How loud oscillator 2 is in the mixer.',
  'studio:m3': 'How loud oscillator 3 is in the mixer.',
  'studio:mr': 'How loud the ring modulator (V1 × V2) is: clangy, bell-like, out-of-tune tones.',
  'studio:kbd': 'Keyboard tracking: how much the filter follows the notes, so high notes stay as bright as low ones.',
  'studio:v3m': 'How much oscillator 3 moves the filter: a wobble on LOW range, a growl on AUDIO.',
  'studio:shm': 'How much the sample-and-hold (random steps) moves the filter: the classic bubbling computer sound.',
  'studio:gain': 'Opens the amp with no note at all: turn it up for a drone.',
  'groove:rec': 'PLAY: the pads play the drums. REC: the pads write steps into the pattern.',
  'groove:accent': 'How much harder the accented steps hit.',
  'kin:vco1eg': 'How far each strike’s decay sweeps oscillator 1’s pitch (left of centre sweeps down): the DFAM “pew”.',
  'kin:vco2eg': 'How far each strike’s decay sweeps oscillator 2’s pitch (left of centre sweeps down).',
  'kin:vcfeg': 'How far each strike sweeps the filter (left of centre sweeps it down).',
  'kin:noisemod': 'How much noise wobbles the filter: from clean to gritty and breathy.',
  'kin:vcfmode': 'LP keeps the lows (round, thuddy); HP keeps the highs (thin, clicky).',
  'kin:sync': 'Locks oscillator 2 to oscillator 1’s cycle: tearing, vocal tones as you move VCO2 FREQ.',
  'undertone:quant': 'Snaps the sequencer’s steps to notes: equal-tempered (12 or 8 per octave) or just intonation (pure, beatless intervals).',
  'undertone:range': 'How far the step knobs reach: ±1, ±2 or ±5 octaves.',
  'undertone:logic': 'When two rhythms land on a step together: OR plays it, XOR skips it (for syncopation).',
  'undertone:vcamode': 'ENV: notes come and go with the envelope. DRONE: it never stops.',
  'polycv:voices': 'How many notes can sound at once; extra notes steal the oldest voice.',
  'tapekeys:sound': 'Which tape is in the machine: strings, flute or choir.',
  'tom:sweep': 'How far the pitch drops after the hit: none for a conga, a lot for a disco tom.',
  'touch:interval': 'The pitch gap between neighbouring plates, in semitones.',
  'turing:change': 'How often a bit flips: far left locks the melody, middle slowly mutates it, far right is pure random.',
  'turing:range': 'How wide the melody spans, in volts (each volt is an octave).',
  'bounce:kickf': 'How hard the KICK button throws the balls back up.',
  'tumbler:len': 'How long each note is held when a ball hits a wall.',
  'tumbler:sides': 'How many walls the drum has (each wall plays its own note).',
  'tumbler:speed': 'How fast the drum spins (left of centre spins it the other way).',
  'orbit:planets': 'How many planets are orbiting (each one a gate).',
  'orbit:ecc': 'How stretched the orbits are: round is steady, stretched swings fast near the sun and slow far away.',
  'life:density': 'How full the colony starts when it reseeds.',
  'flock:cohesion': 'How strongly the birds pull together.',
  'flock:align': 'How strongly each bird matches its neighbours’ heading.',
  'flock:separate': 'How much the birds keep their distance.',
  'chaos:damp': 'Friction: how fast the motion runs down (zero never settles).',
  'ecosystem:growth': 'How fast the rabbits breed.',
  'ecosystem:hunt': 'How good the foxes are at catching rabbits.',
  'ecosystem:starve': 'How fast foxes die off without food.',
  'loop:fb': 'How much of the old loop stays each time you overdub (lower fades older layers away).',
  'loop:slot': 'Which of the four loop slots you’re on.',
  'sample:slices': 'How many equal slices the sample is cut into.',
  'sample:slice': 'Which slice plays.',
  'turntable:brake': 'How long the platter takes to stop when you hit STOP: the slow-down sound.',
  'turntable:wear': 'How worn the record is: crackle, hiss and dull highs.',
  'chop:vintage': 'Old-sampler grit: 12-bit crunch and a darker top.',
  'chop:mode': 'EVEN: slices the sample into 16 equal pads. HITS: cuts at each drum hit.',
  'fourtrack:vari': 'Varispeed: the whole tape faster (higher) or slower (lower).',
  'theremin:snap': 'How much the pitch snaps to the nearest note (left: smooth slides, right: in tune).',
  'omnichord:chord': 'How loud the held chord is.',
  'omnichord:harp': 'How loud the strum plate’s plucks are.',
  'chordwheel:level': 'How loud the built-in pad is.',
  'strike:bright': 'How hard the mallet is: soft and warm to hard and bright.',
  'tanpura:sa': 'The drone’s home note (Sa), in semitones.',
  'tanpura:first': 'The first string’s note: PA (the fifth), MA (the fourth) or NI (the seventh).',
  'tanpura:cycle': 'How long one round of four plucks takes.',
  'tanpura:jawari': 'The buzzing bridge: more is the shimmering, nasal tanpura sound.',
  'gamelan:tuning': 'Slendro (five even-ish steps) or pelog (seven uneven ones): the two gamelan scales.',
  'gamelan:base': 'The lowest note, in semitones.',
  'gamelan:ombak': 'The beating between paired instruments tuned slightly apart: the shimmering gamelan wave.',
  'bowl:water': 'Water in the bowl: wobbles the pitch as it rings.',
  'stylophone:vib': 'A pitch wobble, on or off.',
  'complex:pfreq': 'The principal (the voice you hear) oscillator’s pitch, in octaves.',
  'complex:index': 'How hard the modulator bends the principal: plain, then rich, then clangy.',
  'complex:timbre': 'The wavefolder: folds the wave back on itself for rich, brassy west-coast tones.',
  'complex:track': 'FREE: the modulator stays put. TRACK: it follows V/OCT, so the tone stays the same across notes.',
  'wave:wave': 'Which wave it plays (and morphs between): turn it slowly to hear them blend.',
  'lpg:mode1': 'VCA: just volume. LP: just a filter. COMBO: both at once, the woody west-coast pluck.',
  'lpg:mode2': 'VCA: just volume. LP: just a filter. COMBO: both at once, the woody west-coast pluck.',
  'vca:resp': 'LIN: volume follows the CV straight. EXP: quieter at first then fast, for snappier envelopes.',
  'func:shape': 'The curve of the rise and fall: LOG bows out (snappy), EXP bows in (slow start), middle is straight.',
  'func:cycle': 'ON: it keeps rising and falling by itself, an LFO.',
  'follow:att': 'How fast it follows the input getting louder.',
  'follow:rel': 'How fast it falls when the input gets quieter.',
  'lfo:range': 'LO: slow wobbles. HI: up into audio, so it can be a sound itself.',
  'xy:mode': 'FREE: the dot stays where you leave it. SPRING: it springs back to centre. FLING: throw it and it bounces.',
  'xy:range': 'How many octaves of pitch the pad covers.',
  'xy:morph': 'MORPH: the dot blends between knob settings stored in the four corners.',
  'fold:fold': 'How many times the wave folds back on itself: from smooth to rich and buzzy.',
  'slew:shape': 'LIN: glides at a steady speed. EXP: fast then slowing, like a real portamento.',
  'seq8:quant': 'FREE: the step knobs are smooth voltages. SEMI: they snap to semitones (always notes).',
  'arp:oct': 'How many octaves the arpeggio climbs before it starts again.',
  'arp:latch': 'ON: the arpeggio keeps playing after you let go of the keys.',
  'chord:qual': 'The kind of chord: major (bright), minor (sad), suspended, sevenths, diminished.',
  'chord:inv': 'Which note of the chord is at the bottom: the same chord, voiced higher.',
  'ghost:wait': 'How long you pause before it answers.',
  'ghost:length': 'How many notes its answer runs.',
  'ghost:temper': 'How far it strays from what you played: faithful to adventurous.',
  'ghost:memory': 'How long it remembers your phrases (lower forgets old ideas faster).',
  'progression:mode': 'MAJOR (brighter) or MINOR (darker) key.',
  'progression:mood': 'How adventurous the chords are: safe and settled to borrowed, surprising ones.',
  'progression:bars': 'How many bars each chord lasts.',
  'bandmate:energy': 'How hard the drummer plays: sparse and gentle to busy and loud.',
  'bandmate:phrase': 'How many bars before a fill.',
  'bandmate:human': 'How loose the timing and dynamics are: machine-tight to a real player.',
  'bbd:mod': 'A slow wobble on the delay: the warbly, chorused echo of old pedals.',
  'tape:age': 'How old the tape is: duller, hissier and wobblier.',
  'phaser:center': 'Where the sweeping notches sit: low is a deep whoosh, high a thin swirl.',
  'chamber:damp': 'How soft the walls are: bare concrete rings bright, soft walls absorb.',
  'chamber:width': 'How far apart the two microphones are: wider is a bigger stereo picture.',
  'chamber:tail': 'How long the room keeps ringing.',
  'vocoder:sib': 'Lets the “s” and “t” sounds through, so the words stay clear.',
  'vocoder:freeze': 'HOLD: freezes the current vowel shape on the synth.',
  'vocoder:shift': 'Shifts the voice’s shape up or down: higher sounds smaller and cartoony, lower big and dark.',
  'fuzz:fuzz': 'How much fuzz: sputtering to a full, singing wall.',
  'fuzz:bias': 'Starves the transistors: gated, sputtery, broken fuzz as you turn it.',
  'octave:up': 'An octave above, the ringing Octavia sound.',
  'octave:down': 'An octave below: a fat sub under the note.',
  'octave:down2': 'Two octaves below: a deep growl.',
  'echo:rate': 'The tape speed: how far apart the repeats are. Move it while it plays for the pitch bend.',
  'echo:fb': 'How many repeats: past about three-quarters it builds up into runaway oscillation.',
  'echo:heads': 'Which playback heads are on: each mode is a different rhythm of repeats.',
  'echo:mix': 'How loud the echoes are against the dry sound.',
  'lpedal:level': 'How loud the loop plays back.',
  'amp:sag': 'How much the power supply sags on loud notes: a softer, squishier, “bloomy” feel.',
  'amp:mic': 'Where the microphone sits: on the speaker centre (bright) to the edge (darker).',
  'amp:cab': 'Which speaker cabinet: a small 1×12, a big 4×12, or none (direct).',
  'talkbox:tube': 'How much of the tube’s honk comes through.',
  'console:rel': 'How fast ducked channels come back up after each hit.',
  'glue:schp': 'HPF: the compressor ignores the deep bass, so a kick doesn’t pump the whole mix.',
  'glue:att': 'How fast it clamps down: slower lets the start of each hit punch through.',
  'glue:rel': 'How fast it lets go: AUTO follows the music.',
  'master:ceiling': 'The loudest the output can ever get: the limiter holds peaks under it.',
  'master:width': 'Stereo width: 0 is mono, 1 untouched, 2 extra wide.',
  'djmix:curve': 'SMOOTH: a gentle crossfade. CUT: the scratch curve, opens almost instantly.',
  'atten:a': 'Scales input A: right makes it bigger, left turns it upside down, middle is off.',
  'atten:b': 'Scales input B: right makes it bigger, left turns it upside down, middle is off.',
  'scenes:store': 'STORE: pressing a scene saves the rack into it. RECALL: pressing brings it back.',
  'accident:amount': 'How far each nudged knob moves.',
  'accident:count': 'How many knobs each nudge moves.',
  'accident:evolve': 'How often it nudges on its own: never, to a constant drift.',
  'scope:g1': 'Volts per division for trace 1: lower zooms in on small signals.',
  'scope:g2': 'Volts per division for trace 2.',
  'scope:trig': 'CH1: the picture locks to trace 1 so it holds still. FREE: it just runs.',
  'vector:persist': 'How long the glowing trace lingers.',
  'vector:focus': 'How sharp the beam is.',
  'waterfall:range': 'How much of the quiet end you see: lower hides the faint stuff.',
  'midi:bendRange': 'How far the pitch-bend wheel bends, in semitones.',
  'output:coupling': 'AC blocks steady voltages (safe for speakers). DC passes them (for sending CV out of an audio interface).',
  'monitor:mono': 'MONO: sums left and right, to check the mix still works on one speaker.',
  'monitor:dim': 'DIM: turns everything down 20 dB, without touching your levels.',
  'theremin:range': 'How many octaves your hand covers.',
  'loop:dir': 'Plays the loop forwards or backwards.',
  'sample:loop': 'ONE plays once per trigger; LOOP repeats.',
  'sample:rev': 'Plays forwards or backwards.',
  'fourtrack:rev': 'Plays the tape forwards or backwards.',
  'fourtrack:loop': 'LOOP: the tape goes back to the start when it reaches the end.',
  'loop:rspeed': '½×: records at half speed, so the loop plays back an octave up and twice as fast.',
  'arp:len': 'How long each note of the arpeggio is held: short and staccato to smooth and joined.',
  'turntable:rpm': 'The record speed: 33 or 45 rpm.',
  'strike:inst': 'Which instrument: handpan, steel pan or kalimba.',
  'gamelan:inst': 'Which instrument: saron, bonang or gong.',
  'wah:mode': 'FOOT: you rock the treadle. AUTO: it follows how hard you play.',
  'tom:mode': 'TOM: a pitched tom. CONGA: tight and short.',
  'chaos:mode': 'Which system: a double pendulum (swingy) or the Lorenz attractor (the butterfly).',
  // common words that mean something else here
  'studio:ncol': 'The noise colour: WHITE is bright hiss, PINK is softer and fuller.',
  'kin:seqmod': 'Which oscillators the sequencer’s PITCH knobs play: VCO 2 alone, both, or neither.',
  'kin:vcaatt': 'FAST: every strike snaps in. SLOW: it swells in, softer.',
  'musicbox:motor': 'CRANK: you turn the handle (drag it). MOTOR: it plays by itself at TEMPO.',
  'complex:mfreq': 'The modulator’s frequency: slow for vibrato, up in audio for new metallic tones.',
  'ring:freq': 'The built-in carrier’s frequency, multiplied with the input: bells, metal, steel drums.',
  'master:freq': 'Where the middle band sits: the MID knob boosts or cuts around this frequency.',
  'master:drive': 'Pushes the mix into the limiter: louder and denser, then squashed.',
  'chop:rate': 'Note repeat: how fast a held pad re-triggers.',
  'arp:mode': 'The order the held notes play in: up, down, up and down, random, or as you pressed them.',
  'arp:rate': 'How fast the arpeggio steps (patch CLK to lock it to the tempo).',
  'tr16:rec': 'PLAY: the pads play the drums. REC: hits are written into the pattern as it runs.',
  'omnichord:bass': 'How loud the automatic bass note under each chord is.',
  'omnichord:sustain': 'How long the chord rings on after you let go.',
  'tanpura:decay': 'How long each string rings.',
  'harp:sustain': 'How long the strings ring.',
  'phaser:fb': 'Feeds the output back in: sharper, more ringing, more resonant sweeps.',
  'tune:speed': 'How fast notes are pulled into tune: slow is natural, zero is the hard robotic snap.',
  'tune:mix': 'How much of the corrected voice you hear against the original.',
  'scenes:time': 'How long the rack takes to glide from one scene to the next.',
  'scope:time': 'How much time fits across the screen: short to see a wave’s shape, long for envelopes.',
  'vector:scale': 'Volts per division: lower zooms in on the figure.',
  'loop:speed': 'Varispeed: plays the loop faster (higher) or slower (lower).',
  'tapekeys:speed': 'Nudges the tape speed: the whole instrument a little sharp or flat.',
  'pocketbass:voice': 'The bass sound: a round SUB, a hollow SQUARE, or a squelchy ACID line.',
  'pocketmelody:voice': 'The melody sound: a BELL, a PLUCK or a LEAD.',
  'pocketrobot:voice': 'The lead’s wave: a bright SAW, a hollow SQUARE, or BUZZ (ring-modulated: metallic, robotic).',
  'pocketrobot:glide': 'How long a glide takes: between notes played legato, and into steps marked GLIDE.',
  'pocketrobot:fx': 'The effect: DRY, an ECHO three sixteenths later, or CRUSH (fewer bits, a lower sample rate). B sets how much.',
  'pocketrobot:rec': 'REC: while it plays, every button you press is written into the step it falls nearest.',
  'pocketarcade:voice': 'The lead’s pulse width: THIN (12.5 %) is nasal, HOLLOW (25 %) the classic game lead, SQUARE (50 %) round and woody.',
  'pocketarcade:bass': 'The triangle bass: OFF, BEAT (root and fifth on the beats) or FOLLOW (the lead’s notes, two octaves down).',
  'pocketarcade:drums': 'The noise drums: OFF, BEAT (kick, snare, hats) or BUSY (a running game-music beat).',
  'bandmate:style': 'Which kind of drummer: rock, funk, house, hip-hop or bossa nova.',
  'vision:scene': 'Which living scene is in the tank.',
  'visioncore:scene': 'Which living scene is in the tank.',
  'visionview:scene': 'LINKED shows what the linked tank shows; or pick a scene of its own.',
}
// SEQ-8's step knobs and gates
for (let i = 1; i <= 8; i++) {
  o[`seq8:s${i}`] = `Step ${i}’s pitch.`
  o[`seq8:g${i}`] = `Whether step ${i} plays a note (ON) or rests.`
}
// KIN-8's step pitch and velocity
for (let i = 0; i < 8; i++) {
  o[`kin:p${i}`] = `Step ${i + 1}’s pitch (added to both oscillators).`
  o[`kin:v${i}`] = `How hard step ${i + 1} strikes: louder, and brighter if VELOCITY reaches the filter.`
}
// UNDERTONE's subharmonics, steps and rhythms
for (const v of [1, 2]) {
  for (const s of [1, 2]) o[`undertone:s${v}${s}`] = `Divides oscillator ${v}’s pitch by this number: a note below it from the undertone series.`
  o[`undertone:wave${v}`] = `Oscillator ${v}’s wave (and its subharmonics’): saw or square.`
}
for (let i = 0; i < 4; i++) {
  o[`undertone:a${i}`] = `Sequencer 1’s step ${i + 1}: how far it moves its assigned oscillators.`
  o[`undertone:b${i}`] = `Sequencer 2’s step ${i + 1}: how far it moves its assigned oscillators.`
  o[`undertone:r${i + 1}`] = `Rhythm ${i + 1}: one pulse every this many beats. The four together make polyrhythms.`
}
for (const v of [1, 2]) o[`kin:wave${v}`] = `Oscillator ${v}’s wave: triangle (soft) or square (hollow, buzzy).`
for (const c of ['A', 'B']) {
  o[`euclid:steps${c}`] = `Rhythm ${c}’s length, in steps.`
  o[`euclid:fills${c}`] = `How many hits rhythm ${c} spreads over those steps (3 in 8 is the tresillo).`
  o[`euclid:rot${c}`] = `Shifts rhythm ${c} round by steps: the same pattern starting somewhere else.`
}
for (let i = 1; i <= 4; i++) o[`macro:m${i}`] = `Macro ${i}: moves every knob it learned, at once.`

export const OVERRIDES: Record<string, string> = { ...o, ...MORE_OVERRIDES }
