import type { ModuleSpec } from '../types'
import { BLACK, CREAM } from './panels'

export const follow: ModuleSpec = {
  type: 'follow',
  title: 'FOLLOW',
  name: 'Envelope Follower',
  tagline: 'Turns any signal into an envelope; comparator gate when it crosses the threshold',
  category: 'Modulation',
  hp: 6,
  panel: CREAM,
  inputs: [
    { id: 'in', label: 'IN' },
    { id: 'cmp', label: 'CMP' },
  ],
  outputs: [
    { id: 'env', label: 'ENV' },
    { id: 'gate', label: 'GATE' },
  ],
  params: [
    { id: 'gain', label: 'GAIN', min: 0.5, max: 10, def: 2, curve: 'exp', unit: 'x' },
    { id: 'att', label: 'ATT', min: 0.001, max: 0.5, def: 0.01, curve: 'exp', unit: 's' },
    { id: 'rel', label: 'REL', min: 0.01, max: 2, def: 0.15, curve: 'exp', unit: 's' },
    { id: 'thr', label: 'THRESH', min: 0, max: 10, def: 3 },
  ],
  leds: 1,
  controls: [
    { kind: 'knob', param: 'gain', x: 15.24, y: 24 },
    { kind: 'knob', param: 'att', x: 8.5, y: 41, size: 'S' },
    { kind: 'knob', param: 'rel', x: 22, y: 41, size: 'S' },
    { kind: 'knob', param: 'thr', x: 11, y: 57, size: 'S' },
    { kind: 'led', index: 0, x: 22, y: 57, color: '#3bff6b' },
    { kind: 'in', jack: 'in', x: 8.5, y: 80 },
    { kind: 'in', jack: 'cmp', x: 22, y: 80 },
    { kind: 'out', jack: 'env', x: 8.5, y: 106 },
    { kind: 'out', jack: 'gate', x: 22, y: 106 },
  ],
}

export const logic: ModuleSpec = {
  type: 'logic',
  title: 'LOGIC',
  name: 'Logic',
  tagline: 'AND, OR, XOR, NOT and a toggle flip-flop for gates and clocks',
  category: 'Utilities',
  hp: 8,
  panel: BLACK,
  inputs: [
    { id: 'a', label: 'A' },
    { id: 'b', label: 'B' },
    { id: 'r', label: 'RST' },
  ],
  outputs: [
    { id: 'and', label: 'AND' },
    { id: 'or', label: 'OR' },
    { id: 'xor', label: 'XOR' },
    { id: 'not', label: 'NOT A' },
    { id: 'flip', label: 'FLIP' },
  ],
  params: [],
  leds: 5,
  controls: [
    { kind: 'in', jack: 'a', x: 8, y: 26 },
    { kind: 'in', jack: 'b', x: 20.3, y: 26 },
    { kind: 'in', jack: 'r', x: 32.6, y: 26 },
    { kind: 'text', text: 'FLIP TOGGLES ON A', x: 20.3, y: 37, size: 1.6 },
    { kind: 'out', jack: 'and', x: 11, y: 56 },
    { kind: 'out', jack: 'or', x: 29.6, y: 56 },
    { kind: 'out', jack: 'xor', x: 11, y: 78 },
    { kind: 'out', jack: 'not', x: 29.6, y: 78 },
    { kind: 'out', jack: 'flip', x: 20.3, y: 101 },
    { kind: 'led', index: 0, x: 4, y: 64, color: '#ff3b2f' },
    { kind: 'led', index: 1, x: 36.6, y: 64, color: '#ff3b2f' },
    { kind: 'led', index: 2, x: 4, y: 86, color: '#ff3b2f' },
    { kind: 'led', index: 3, x: 36.6, y: 86, color: '#ff3b2f' },
    { kind: 'led', index: 4, x: 29, y: 108, color: '#ff3b2f' },
  ],
}

export const func: ModuleSpec = {
  type: 'func',
  title: 'FUNC',
  name: 'Function Generator',
  tagline: 'Maths-style rise/fall: envelope, slew, or cycling LFO with curve shaping',
  category: 'Modulation',
  hp: 8,
  panel: CREAM,
  inputs: [
    { id: 'trig', label: 'TRIG' },
    { id: 'in', label: 'IN' },
    { id: 'cyc', label: 'CYC' },
    { id: 'rise', label: 'RISE' },
    { id: 'fall', label: 'FALL' },
  ],
  outputs: [
    { id: 'out', label: 'OUT' },
    { id: 'eor', label: 'EOR' },
    { id: 'eoc', label: 'EOC' },
    { id: 'inv', label: 'INV' },
  ],
  params: [
    { id: 'rise', label: 'RISE', min: 0.001, max: 10, def: 0.1, curve: 'exp', unit: 's' },
    { id: 'fall', label: 'FALL', min: 0.001, max: 10, def: 0.3, curve: 'exp', unit: 's' },
    { id: 'shape', label: 'LOG↔EXP', min: -1, max: 1, def: 0, unit: '%' },
    { id: 'level', label: 'LEVEL', min: -1, max: 1, def: 1, unit: '%' },
    { id: 'cycle', label: 'CYCLE', min: 0, max: 1, def: 0, stepped: true, options: ['OFF', 'ON'] },
  ],
  leds: 1,
  controls: [
    { kind: 'knob', param: 'rise', x: 11, y: 26 },
    { kind: 'knob', param: 'fall', x: 29.6, y: 26 },
    { kind: 'knob', param: 'shape', x: 11, y: 45, size: 'S' },
    { kind: 'knob', param: 'level', x: 29.6, y: 45, size: 'S' },
    { kind: 'switch', param: 'cycle', x: 20.3, y: 57 },
    { kind: 'led', index: 0, x: 29.6, y: 58, color: '#ff3b2f' },
    { kind: 'in', jack: 'trig', x: 8, y: 76 },
    { kind: 'in', jack: 'in', x: 20.3, y: 76 },
    { kind: 'in', jack: 'cyc', x: 32.6, y: 76 },
    { kind: 'in', jack: 'rise', x: 8, y: 94 },
    { kind: 'in', jack: 'fall', x: 20.3, y: 94 },
    { kind: 'out', jack: 'out', x: 32.6, y: 96 },
    { kind: 'out', jack: 'eor', x: 8, y: 113 },
    { kind: 'out', jack: 'eoc', x: 20.3, y: 113 },
    { kind: 'out', jack: 'inv', x: 32.6, y: 113 },
  ],
}
