import type { Control, ModuleSpec } from '../types'
import { SAND } from './panels'

const BAY_X = [266, 281, 296, 311]

const inputs = [
  { id: 'pitch', label: 'PITCH' },
  { id: 'gate', label: 'GATE' },
  { id: 'fm1', label: 'V1 FM' },
  { id: 'fm2', label: 'V2 FM' },
  { id: 'fm3', label: 'V3 FM' },
  { id: 'vcfin', label: 'VCF IN' },
  { id: 'vcfcv', label: 'VCF CV' },
  { id: 'vcain', label: 'VCA IN' },
  { id: 'vcacv', label: 'VCA CV' },
  { id: 'shin', label: 'S&H IN' },
  { id: 'shclk', label: 'S&H CLK' },
  { id: 'revin', label: 'REV IN' },
]
const outputs = [
  { id: 'v1', label: 'V1' },
  { id: 'v2', label: 'V2' },
  { id: 'v3', label: 'V3' },
  { id: 'noise', label: 'NOISE' },
  { id: 'ring', label: 'RING' },
  { id: 'vcf', label: 'VCF' },
  { id: 'vca', label: 'VCA' },
  { id: 'adsr', label: 'ADSR' },
  { id: 'ar', label: 'AR' },
  { id: 'sh', label: 'S&H' },
  { id: 'lfo', label: 'LFO' },
  { id: 'out', label: 'OUT' },
]

const knob = (param: string, x: number, y: number, size: 'L' | 'M' | 'S' = 'M', label?: string): Control => ({
  kind: 'knob',
  param,
  x,
  y,
  size,
  label,
})

/** 2600-style semi-modular: three VCOs, noise, ring mod, mixer, ladder VCF,
 *  ADSR + AR, VCA, LFO-clocked S&H and spring reverb, all pre-wired; twelve
 *  switched patch-bay inputs override the internal connections. */
export const studio: ModuleSpec = {
  type: 'studio',
  title: 'STUDIO-3',
  name: 'STUDIO-3 Semi-Modular (2600-style)',
  tagline: 'Three VCOs, noise, ring mod, VCF, ADSR+AR, S&H, spring: pre-wired, patch bay overrides',
  category: 'Systems',
  hp: 64,
  panel: SAND,
  inputs,
  outputs,
  params: [
    { id: 't1', label: 'TUNE', min: -2, max: 2, def: 0, unit: 'oct' },
    { id: 'f1', label: 'FINE', min: -1, max: 1, def: 0, unit: 'st' },
    { id: 'fm1', label: 'FM ← V2', min: 0, max: 1, def: 0, unit: '%' },
    { id: 'pw1', label: 'WIDTH', min: 0.05, max: 0.95, def: 0.5, unit: '%' },
    { id: 't2', label: 'TUNE', min: -2, max: 2, def: 0, unit: 'oct' },
    { id: 'f2', label: 'FINE', min: -1, max: 1, def: 0.07, unit: 'st' },
    { id: 'pw2', label: 'WIDTH', min: 0.05, max: 0.95, def: 0.35, unit: '%' },
    { id: 't3', label: 'TUNE', min: -2, max: 2, def: -1, unit: 'oct' },
    { id: 'f3', label: 'FINE', min: -1, max: 1, def: -0.05, unit: 'st' },
    { id: 'lf3', label: 'V3 RANGE', min: 0, max: 1, def: 0, stepped: true, options: ['AUDIO', 'LOW'] },
    { id: 'm1', label: 'V1', min: 0, max: 1, def: 0.7, unit: '%' },
    { id: 'm2', label: 'V2', min: 0, max: 1, def: 0.6, unit: '%' },
    { id: 'm3', label: 'V3', min: 0, max: 1, def: 0.3, unit: '%' },
    { id: 'mn', label: 'NOISE', min: 0, max: 1, def: 0, unit: '%' },
    { id: 'mr', label: 'RING', min: 0, max: 1, def: 0, unit: '%' },
    { id: 'ncol', label: 'NOISE', min: 0, max: 1, def: 0, stepped: true, options: ['WHITE', 'PINK'] },
    { id: 'cut', label: 'CUTOFF', min: 30, max: 18000, def: 900, curve: 'exp', unit: 'Hz' },
    { id: 'res', label: 'RESONANCE', min: 0, max: 1.1, def: 0.3, unit: '%' },
    { id: 'kbd', label: 'KBD', min: 0, max: 1, def: 0.5, unit: '%' },
    { id: 'env', label: 'ENV', min: -1, max: 1, def: 0.45, unit: '%' },
    { id: 'v3m', label: 'V3', min: 0, max: 1, def: 0, unit: '%' },
    { id: 'shm', label: 'S&H', min: 0, max: 1, def: 0, unit: '%' },
    { id: 'a', label: 'ATTACK', min: 0.001, max: 10, def: 0.005, curve: 'exp', unit: 's' },
    { id: 'd', label: 'DECAY', min: 0.001, max: 10, def: 0.4, curve: 'exp', unit: 's' },
    { id: 's', label: 'SUSTAIN', min: 0, max: 1, def: 0.4, unit: '%' },
    { id: 'r', label: 'RELEASE', min: 0.001, max: 10, def: 0.4, curve: 'exp', unit: 's' },
    { id: 'ara', label: 'ATTACK', min: 0.001, max: 10, def: 0.003, curve: 'exp', unit: 's' },
    { id: 'arr', label: 'RELEASE', min: 0.001, max: 10, def: 0.35, curve: 'exp', unit: 's' },
    { id: 'gain', label: 'INITIAL', min: 0, max: 1, def: 0, unit: '%' },
    { id: 'rate', label: 'RATE', min: 0.05, max: 30, def: 4, curve: 'exp', unit: 'Hz' },
    { id: 'rev', label: 'MIX', min: 0, max: 1, def: 0.25, unit: '%' },
    { id: 'rdec', label: 'DECAY', min: 0, max: 1, def: 0.5, unit: '%' },
    { id: 'vol', label: 'VOLUME', min: 0, max: 1, def: 0.6, unit: '%' },
  ],
  leds: 3,
  controls: [
    { kind: 'section', x: 3, y: 16, w: 48, h: 48, label: 'VCO 1' },
    knob('t1', 15, 31),
    knob('f1', 39, 31),
    knob('fm1', 15, 51),
    knob('pw1', 39, 51),
    { kind: 'section', x: 53, y: 16, w: 48, h: 48, label: 'VCO 2' },
    knob('t2', 65, 31),
    knob('f2', 89, 31),
    knob('pw2', 77, 51),
    { kind: 'section', x: 103, y: 16, w: 40, h: 48, label: 'VCO 3' },
    knob('t3', 113, 31),
    knob('f3', 133, 31),
    { kind: 'switch', param: 'lf3', x: 123, y: 51 },
    { kind: 'section', x: 145, y: 16, w: 58, h: 48, label: 'MIXER' },
    knob('m1', 152, 31, 'S'),
    knob('m2', 164, 31, 'S'),
    knob('m3', 176, 31, 'S'),
    knob('mn', 188, 31, 'S'),
    knob('mr', 200, 31, 'S', 'RING'),
    { kind: 'switch', param: 'ncol', x: 174, y: 51 },
    { kind: 'section', x: 205, y: 16, w: 50, h: 48, label: 'FILTER' },
    knob('cut', 218, 30, 'L'),
    knob('res', 243, 30),
    knob('kbd', 211, 52, 'S'),
    knob('env', 223, 52, 'S'),
    knob('v3m', 235, 52, 'S'),
    knob('shm', 247, 52, 'S'),

    { kind: 'section', x: 3, y: 67, w: 60, h: 48, label: 'ADSR' },
    knob('a', 13, 85),
    knob('d', 27, 85),
    knob('s', 41, 85),
    knob('r', 55, 85),
    { kind: 'section', x: 65, y: 67, w: 32, h: 48, label: 'AR' },
    knob('ara', 74, 85),
    knob('arr', 88, 85),
    { kind: 'section', x: 99, y: 67, w: 32, h: 48, label: 'VCA' },
    knob('gain', 110, 85),
    { kind: 'led', index: 0, x: 124, y: 85, color: '#ff3b2f' },
    { kind: 'section', x: 133, y: 67, w: 40, h: 48, label: 'LFO · S&H' },
    knob('rate', 145, 85),
    { kind: 'led', index: 1, x: 162, y: 85, bipolar: true },
    { kind: 'section', x: 175, y: 67, w: 38, h: 48, label: 'REVERB' },
    knob('rev', 185, 85),
    knob('rdec', 203, 85),
    { kind: 'section', x: 215, y: 67, w: 40, h: 48, label: 'OUTPUT' },
    knob('vol', 228, 85),
    { kind: 'led', index: 2, x: 246, y: 85, color: '#3bff6b' },

    { kind: 'section', x: 258, y: 16, w: 64, h: 99, label: 'PATCH BAY' },
    ...inputs.map((j, i): Control => ({ kind: 'in', jack: j.id, x: BAY_X[i % 4], y: [29, 44, 59][Math.floor(i / 4)] })),
    ...outputs.map((j, i): Control => ({ kind: 'out', jack: j.id, x: BAY_X[i % 4], y: [80, 96, 111][Math.floor(i / 4)] })),
  ],
}
