import type { Patch } from '../types'
import { RackBuilder } from './builder'

/** Two-oscillator subtractive voice played from the keyboard (the original demo). */
export function classicMono(): Patch {
  const b = new RackBuilder()
  const midi = b.add('midi', 0, 0)
  const vco1 = b.add('vco', 0, 8, { pwm: 0.35 })
  const vco2 = b.add('vco', 0, 20, { fine: 0.09 })
  const mix = b.add('mixer', 0, 32, { l1: 0.7, l2: 0.7, l3: 0, l4: 0 })
  const vcf = b.add('vcf', 0, 40, { cutoff: 420, res: 0.45, drive: 1.2, cv: 0.42 })
  const vca = b.add('vca', 0, 50)
  const envAmp = b.add('adsr', 0, 56, { a: 0.004, d: 0.35, s: 0.75, r: 0.35 })
  const envFlt = b.add('adsr', 0, 64, { a: 0.006, d: 0.45, s: 0.25, r: 0.4 })
  const lfo = b.add('lfo', 0, 72, { rate: 0.35 })
  const out = b.add('output', 0, 80)
  b.add('noise', 0, 86)
  b.add('mult', 0, 90)
  const scope = b.add('scope', 1, 0, { time: 0.01 })
  b.wire(midi, 'pitch', vco1, 'voct')
  b.wire(midi, 'pitch', vco2, 'voct')
  b.wire(midi, 'gate', envAmp, 'gate')
  b.wire(midi, 'gate', envFlt, 'gate')
  b.wire(vco1, 'sqr', mix, 'in1')
  b.wire(vco2, 'saw', mix, 'in2')
  b.wire(mix, 'out', vcf, 'in')
  b.wire(envFlt, 'env', vcf, 'cv')
  b.wire(vcf, 'lp4', vca, 'in')
  b.wire(envAmp, 'env', vca, 'cv')
  b.wire(lfo, 'tri', vco1, 'pwm')
  b.wire(vca, 'out', out, 'l')
  b.wire(vca, 'out', scope, 'ch1')
  b.wire(envFlt, 'env', scope, 'ch2')
  return b.build()
}

/** MONO-1 lead through a BBD echo and spring tank. Play it from the keyboard. */
export function monoLead(): Patch {
  const b = new RackBuilder()
  const mono = b.add('mono', 0, 0, {
    vol: 0, wave: 0.25, cutoff: 1100, res: 0.5, envamt: 0.45, glide: 0.08, lfoamt: 0.08, lrate: 5, pwm: 0.25,
  })
  const bbd = b.add('bbd', 0, 40, { time: 0.375, fb: 0.45, mix: 0.35, mod: 0.25 })
  const spring = b.add('spring', 0, 50, { decay: 0.55, mix: 0.3 })
  const out = b.add('output', 0, 58, { vol: 1 })
  const scope = b.add('scope', 0, 64, { time: 0.01 })
  b.wire(mono, 'vca', bbd, 'in')
  b.wire(bbd, 'out', spring, 'in')
  b.wire(spring, 'out', out, 'l')
  b.wire(mono, 'vca', scope, 'ch1')
  b.wire(mono, 'env', scope, 'ch2')
  return b.build()
}

/** Self-playing: a slow clock samples noise, quantised to a pentatonic scale,
 *  over a soft drone (a triangle two octaves down, barely detuned); a gently
 *  swept SVF, slow swells, a long BBD and a big, dark plate. */
export function ambient(): Patch {
  const b = new RackBuilder()
  const clock = b.add('clock', 0, 0, { bpm: 50 })
  const div = b.add('div', 0, 8)
  const sh = b.add('sh', 0, 14)
  const atten = b.add('atten', 0, 20, { a: 0.17 })
  const quant = b.add('quant', 0, 26, { scale: 4 })
  const vco1 = b.add('vco', 0, 34)
  const vco2 = b.add('vco', 0, 46, { coarse: -2, fine: 0.04 })
  const mix = b.add('mixer', 0, 58, { l1: 0.75, l2: 0.4, l3: 0, l4: 0 })
  const svf = b.add('svf', 0, 66, { cutoff: 650, res: 0.12, cv: 0.25 })
  const vca = b.add('vca', 0, 76, { gain: 0.15 })
  const env = b.add('adsr', 0, 82, { a: 2.5, d: 3, s: 0.6, r: 6 })
  const lfo = b.add('lfo', 0, 90, { rate: 0.05 })
  const bbd = b.add('bbd', 1, 0, { time: 0.6, fb: 0.5, mix: 0.35, mod: 0.15 })
  const plate = b.add('plate', 1, 10, { decay: 0.85, damp: 0.85, pre: 0.04, mix: 0.45 })
  const out = b.add('output', 1, 20, { vol: 1 })
  const scope = b.add('scope', 1, 26, { time: 0.05 })
  b.wire(clock, 'x1', div, 'clk')
  b.wire(div, 'd3', sh, 'trig')
  b.wire(div, 'd3', env, 'gate')
  b.wire(sh, 'out', atten, 'a')
  b.wire(atten, 'a', quant, 'in')
  b.wire(quant, 'out', vco1, 'voct')
  b.wire(vco1, 'tri', mix, 'in1')
  b.wire(vco2, 'tri', mix, 'in2')
  b.wire(mix, 'out', svf, 'in')
  b.wire(lfo, 'sin', svf, 'cv')
  b.wire(svf, 'lp', vca, 'in')
  b.wire(env, 'env', vca, 'cv')
  b.wire(vca, 'out', bbd, 'in')
  b.wire(bbd, 'out', plate, 'in')
  b.wire(plate, 'l', out, 'l')
  b.wire(plate, 'r', out, 'r')
  b.wire(vca, 'out', scope, 'ch1')
  b.wire(env, 'env', scope, 'ch2')
  return b.build()
}

/** Self-playing west-coast plucks: random quantised notes, a sine folded by
 *  its own envelope (brighter on the strike), into a spring. */
export function westCoast(): Patch {
  const b = new RackBuilder()
  const clock = b.add('clock', 0, 0, { bpm: 105 })
  const sh = b.add('sh', 0, 8)
  const atten = b.add('atten', 0, 14, { a: 0.3 })
  const quant = b.add('quant', 0, 20, { scale: 3 })
  const vco = b.add('vco', 0, 28, { coarse: -1 })
  const fold = b.add('fold', 0, 40, { fold: 1.2, cv: 0.6 })
  const vca = b.add('vca', 0, 48, { resp: 1 })
  const env = b.add('adsr', 0, 54, { a: 0.002, d: 0.25, s: 0, r: 0.25 })
  const spring = b.add('spring', 0, 62, { decay: 0.6, mix: 0.35 })
  const out = b.add('output', 0, 70, { vol: 0.8 })
  const scope = b.add('scope', 0, 76, { time: 0.02 })
  b.wire(clock, 'x2', sh, 'trig')
  b.wire(clock, 'x2', env, 'gate')
  b.wire(sh, 'out', atten, 'a')
  b.wire(atten, 'a', quant, 'in')
  b.wire(quant, 'out', vco, 'voct')
  b.wire(vco, 'sin', fold, 'in')
  b.wire(env, 'env', fold, 'cv')
  b.wire(fold, 'out', vca, 'in')
  b.wire(env, 'env', vca, 'cv')
  b.wire(vca, 'out', spring, 'in')
  b.wire(spring, 'out', out, 'l')
  b.wire(fold, 'out', scope, 'ch1')
  b.wire(env, 'env', scope, 'ch2')
  return b.build()
}
